### ISSUE TITLE
AttributeError: 'DiDegreeView' object has no attribute 'items'

### ISSUE THREAD

**Issue by Kotresh17** [ulikoehler/OTR#1]
AttributeError                            Traceback (most recent call last)
<ipython-input-19-29dbda5adc86> in <module>()
      4 contour_analyzer.filter_contours(min_area=400)
      5 contour_analyzer.build_graph()
----> 6 contour_analyzer.remove_non_table_nodes()
      7 contour_analyzer.compute_contour_bounding_boxes(e)
      8 contour_analyzer.separate_supernode(f)

~/transfer_learning/table_data/OTR/TableRecognition.py in remove_non_table_nodes(self)
    208         self.supernode_idx = max(self.g.degree().items(), key=operator.itemgetter(1))[0]
    209         for i in range(len(self.contours)):
--> 210             if self.contours[i] is None: continue
    211             nxt, prev, first_child, parent = self.hierarchy[0, i]
    212             # Remove node if it has a non-supernode node as parent

AttributeError: 'DiDegreeView' object has no attribute 'items'

**Comment by Sousouam** [comment]
I get the same error when I run test-otr.py 
Please help to fix this error !

**Comment by Kotresh17** [comment]
try this it works
 self.supernode_idx = max(dict(self.g.degree()).items(), key=operator.itemgetter(1))[0]
